### ISSUE TITLE
Launching Paraview results in NoVNC error

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_osc_paraview#5]
Launching Paraview results in NoVNC error, whose message appears above the screen persistently.

<img width="1540" alt="screen shot 2017-06-18 at 5 19 31 pm" src="https://user-images.githubusercontent.com/512333/27264355-98593d30-544a-11e7-9d03-04990bb20301.png">

<img width="1540" alt="screen shot 2017-06-18 at 5 19 40 pm" src="https://user-images.githubusercontent.com/512333/27264357-9b8af444-544a-11e7-99bb-7f8665b6d9ad.png">

**Comment by nickjer** [comment]
I am not experiencing this error from my home computer (Linux / Chrome). What OS and browser are you using? Also can you open up the console and see what javascript errors there are.

**Comment by ericfranz** [comment]
I can no longer reproduce this.
